// Usage (from the project folder):
//   cat data.js engine.js tools/rep_tail.js > /tmp/rep.js && cat data.js engine.js tools/pvp_tail.js > /tmp/pvp.js
//   H=$(cat data.js > /tmp/d.js && echo "console.log(HERO_ORDER.join(','))" >> /tmp/d.js && node /tmp/d.js)
//   node /tmp/rep.js heroes $H 55 > /tmp/rh.json && node /tmp/rep.js builds $H 28 > /tmp/rb.json
//   node /tmp/pvp.js team 6000 > /tmp/p3.json && node /tmp/pvp.js duel 16 > /tmp/p1.json
//   cat data.js tools/gen_simstats.js > /tmp/gen.js && node /tmp/gen.js 0.9 /tmp/rh.json /tmp/rb.json /tmp/p3.json /tmp/p1.json
//   (data.js is too large to pass inline with node -e, so always concatenate into a file)
const fs = require('fs');
const [ver, fh, fb, f3, f1] = process.argv.slice(-5);
const H = JSON.parse(fs.readFileSync(fh, 'utf8')), Bd = JSON.parse(fs.readFileSync(fb, 'utf8')), T = JSON.parse(fs.readFileSync(f3, 'utf8')), D = JSON.parse(fs.readFileSync(f1, 'utf8'));
const imp = A => A.dmg + A.heal + 0.75 * A.shield + 0.35 * A.taken + 120 * A.kills + 30 * (A.buffs + A.debuffs);
const r1 = x => Math.round(x * 10) / 10;
const R = A => ({ n: A.n, win: r1(A.win / A.n * 100), imp: r1(imp(A) / A.turns), dmg: r1(A.dmg / A.turns), sup: r1((A.heal + A.shield) / A.turns), falls: r1(A.kos / A.n * 100), taken: r1(A.taken / A.maxHp * 100), acts: r1(A.acts / A.turns * 100), ults: r1(A.ults / A.n), crit: r1(A.crits / Math.max(1, A.hits) * 100), hit: r1(A.hits / Math.max(1, A.hits + A.misses) * 100), share: r1(A.dmg / A.teamDmg * 100) });
const out = { v: ver, stages: ['cult', 'prophet', 'malakai', 'mirror', 'elphi', 'chosen', 'gate', 'warden', 'shadows', 'yunze', 'harry'], heroes: {}, builds: {}, team3: T.team, games3: T.games, draws3: T.draws, duel: D.duel, matrix: D.matrix, duelN: D.perPair || 32 };
for (const h of HERO_ORDER) { out.heroes[h] = R(H[h + ':balanced']); out.heroes[h].t3 = T.team[h]; out.heroes[h].d1 = D.duel[h]; out.builds[h] = {}; for (const b of BUILDS[h]) out.builds[h][b.id] = R(Bd[h + ':' + b.id]); }
fs.writeFileSync('simstats.js', '/* Generated by the balance simulator: campaign fights, 3v3 hero battles and 1v1 duels. */\nconst SIM_STATS = ' + JSON.stringify(out) + ';\n');
console.log('simstats.js written for v' + ver);
